[project]
name = "python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "eth-tester>=0.12.0b2",
    "py-evm>=0.10.1b2",
    "web3>=7.4.0",
]
